### ISSUE TITLE
[serialization] Ensure OnceCell cache is always compatible with compact serialization

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/fastcrypto#330] opened 2022-12-30 11:36 UTC
A test that all to_bytes methods we have across our code base are consistent would suffice. Mentioning this, because it's another "public" method where users can indirectly extract the "serialized" object.

**Comment by benr-ml** [comment] 2023-01-08 12:02
duplicate of #326

**Closed** 2023-01-08 12:02 UTC
